// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions; 
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA4dYjPDKhjCbw_JZAs_i9YUxlKtHJZhI',
    appId: '1:218238886185:web:a9adf4b942686a3e639738',
    messagingSenderId: '218238886185',
    projectId: 'da-crust-dev',
    authDomain: 'da-crust-dev.firebaseapp.com',
    storageBucket: 'da-crust-dev.firebasestorage.app',
    measurementId: 'G-ZEFXPFKEFP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3T2A9r0MvxHjGmbAIqeVwIzHLIjkg26o',
    appId: '1:218238886185:android:14c3cd829b9094a5639738',
    messagingSenderId: '218238886185',
    projectId: 'da-crust-dev',
    storageBucket: 'da-crust-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0yjOi6MjmvhOJuZV-Q0jn5OuE_1I-XtU',
    appId: '1:218238886185:ios:081a78158599ebf6639738',
    messagingSenderId: '218238886185',
    projectId: 'da-crust-dev',
    storageBucket: 'da-crust-dev.firebasestorage.app',
    iosBundleId: 'com.example.daCrustApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0yjOi6MjmvhOJuZV-Q0jn5OuE_1I-XtU',
    appId: '1:218238886185:ios:081a78158599ebf6639738',
    messagingSenderId: '218238886185',
    projectId: 'da-crust-dev',
    storageBucket: 'da-crust-dev.firebasestorage.app',
    iosBundleId: 'com.example.daCrustApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCA4dYjPDKhjCbw_JZAs_i9YUxlKtHJZhI',
    appId: '1:218238886185:web:108625d7e4b201ec639738',
    messagingSenderId: '218238886185',
    projectId: 'da-crust-dev',
    authDomain: 'da-crust-dev.firebaseapp.com',
    storageBucket: 'da-crust-dev.firebasestorage.app',
    measurementId: 'G-FXDW1JH7YR',
  );
}
