// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAACeDJ_zJefg0_IdecFHpY931GQ1G0Jp4',
    appId: '1:128457479265:web:304ef141fe362fe2ad4620',
    messagingSenderId: '128457479265',
    projectId: 'da-crust-prod',
    authDomain: 'da-crust-prod.firebaseapp.com',
    storageBucket: 'da-crust-prod.firebasestorage.app',
    measurementId: 'G-JSC0R1J4J9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApmaru2B7vjdGdeYs1tzuMDZ-sQYpmLB4',
    appId: '1:128457479265:android:c4403157cc311e7dad4620',
    messagingSenderId: '128457479265',
    projectId: 'da-crust-prod',
    storageBucket: 'da-crust-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAuqnkZVI5Ggt9d7utN4PzhMFsCyEAEaw',
    appId: '1:128457479265:ios:008d3fbe4735f2fbad4620',
    messagingSenderId: '128457479265',
    projectId: 'da-crust-prod',
    storageBucket: 'da-crust-prod.firebasestorage.app',
    iosBundleId: 'com.example.daCrustApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAuqnkZVI5Ggt9d7utN4PzhMFsCyEAEaw',
    appId: '1:128457479265:ios:008d3fbe4735f2fbad4620',
    messagingSenderId: '128457479265',
    projectId: 'da-crust-prod',
    storageBucket: 'da-crust-prod.firebasestorage.app',
    iosBundleId: 'com.example.daCrustApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAACeDJ_zJefg0_IdecFHpY931GQ1G0Jp4',
    appId: '1:128457479265:web:2ffb442664414d8dad4620',
    messagingSenderId: '128457479265',
    projectId: 'da-crust-prod',
    authDomain: 'da-crust-prod.firebaseapp.com',
    storageBucket: 'da-crust-prod.firebasestorage.app',
    measurementId: 'G-BTHH3NBDMZ',
  );
}
